
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
gen:
  build:
    name: "shop"
    arch: "amd64"
    system: "linux,darwin,windows"
    mod: ""
    cgo: 0
  dao:
    _ link: "mysql:root:123456@tcp(127.0.0.1:3306)/shop?loc=Local"
    removePrefix: "gf_"
    descriptionTag: true
    noModelComment: true


database:
  type: "mysql"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  pass: 123456
  name: "shop"
  timezone: "Asia/Shanghai"
  debug: true

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app